### ISSUE TITLE
A mix task to format files in a project

### ISSUE THREAD

**Issue by gmile** [uohzxela/ex_format#13]
It would be super useful to have a mix task that would format the code & write formatted code into files automatically for the entire project, including tests.

**Comment by uohzxela** [comment]
Hi @gmile! Thanks for your suggestion. This is definitely something I'm planning to do after most of the features are completed. Right now, there are still some features I'd like to tackle, namely line splitting, hex literals and a couple of indentation-related rules.

@whatyouhide, what do you think of starting on the mix task tooling the week after? For next week, I'm planning to work on hex literals and the remaining indentation-related rules. I think it'd be very helpful for the stress testing phase down the road as well.

**Comment by whatyouhide** [comment]
@uohzxela I am personally quite on the :-1: side on a Mix task at this point. It will not help testing of ex_format and it's very early to stress test things out of ex_format for now. Also, a Mix task for this should be straightforward to write so users can start by writing one themselves if they need it now.

**Comment by uohzxela** [comment]
@gmile sounds like we don't have the bandwidth for now, but I'm going to leave this issue open so that we can revisit it in the near future. Until then, you are super welcome to contribute. :)

**Comment by uohzxela** [comment]
As per #65, we need to have the following:

> 
> Finally create the crowd favorite mix format task, which takes a list of wildcards and formats all the files that match each wildcard (mix format lib/**/*.ex config/**/*.exs). This should only use format/1 and do the file reading/writing "in private" without exposing anything
> 
> Write docs for mix format

**Comment by lpil** [comment]
Can this be closed now? :)
