### ISSUE TITLE
Split every pipe if there's intended line break in pipeline

### ISSUE THREAD

**Issue by uohzxela** [uohzxela/ex_format#20]

**Comment by binaryseed** [comment]
Is this the case you are referring to?

https://github.com/uohzxela/ex_format/blob/master/test/test_cases/pipeline_indentations_good.ex#L7-L9

```elixir
input |> Some.verylongcall() |> Again.verylonglongcall()
|> AgainAgain.verylonglongcall()
|> AgainAgainAgain.verylonglongcall()
```

Where this would be the new "good" version:

```elixir
input 
|> Some.verylongcall()
|> Again.verylonglongcall()
|> AgainAgain.verylonglongcall()
|> AgainAgainAgain.verylonglongcall()
```

This seems worthy of a simple rule in the style guide.. Something like "In a multi-line pipeline, place each function call on a new line"

https://github.com/lexmag/elixir-style-guide#pipeline-operator

**Comment by uohzxela** [comment]
Yeah that's what I meant. It's an implicit rule I guess, but it's good to spell it out explicitly in the style guide though.
