### ISSUE TITLE
Multiline maps and lists should start on the same line as assignment

### ISSUE THREAD

**Issue by whatyouhide** [uohzxela/ex_format#29]
```elixir
map = %{
  a: 1,
}
```

should be left alone and not turned into

```elixir
map =
  %{
    a: 1,
  }
```

Same for lists.

**Comment by lpil** [comment]
Is this 

```elixir
map = %{
  a: 1,
  b: 2,
}
```

preferred over this

```elixir
map = %{a: 1,
        b: 2}
```
with regards to the closing brace? For some reason I thought that the latter is what is done in the compiler.

**Comment by whatyouhide** [comment]
The first one is preferred in "modern" Elixir. @josevalim confirm?

**Comment by whatyouhide** [comment]
Btw the compiler is not the best example of Elixir code out there stylistically speakin :)

**Comment by lpil** [comment]
Doh, I've been using it as my reference! Thanks for the help

**Comment by josevalim** [comment]
So Elixir was used to do this:

```elixir
%{foo: 1,
  bar: 2}
```

But now we have changed it to:

```elixir
%{
  foo: 1,
  bar: 2
}
```

When we had the former, I would indent the code like this:

```elixir
map =
  %{foo: 1,
    bar: 2}
```

but now that we change the map formatting, I find this one too verbose:

```elixir
map =
  %{
    foo: 1,
    bar: 2
  }
```

so we should probably stick with:

```elixir
map = %{
  foo: 1,
  bar: 2
}
```

Keep in mind that this only applies to key-value pairs. Function calls, lists and so on they always run until the end of the line:

```elixir
list =
  [1, 2, 3, 4, 5, 6, 7, 8, 9,
   10, 11, 12]

fun_call =
  some_fun(foo, bar, baz,
          baz)
```

**Comment by lpil** [comment]
Thanks Jose. :)

**Comment by josevalim** [comment]
@lpil you are welcome! and feel free to dispute the post above. That's how we have been doing things but they are definitely up to debate - as we just changed maps.

**Comment by lpil** [comment]
I am a little surprised by the function args, I would have gone for one of these.

```elixir
some_fun(foo,
         bar,
         baz,
         baz)
```
```elixir
some_fun(
  foo,
  bar,
  baz
  baz
)
```

**Comment by josevalim** [comment]
@lpil the issue is that some functions take 6 or 8 arguments. Usually a big pattern matching on the first argument and then 5 or 6 following. If we do one per line, we have this:

```elixir
def some_function(
  %{module: module, function: function},
  arg1,
  arg2,
  arg3,
  arg4
) do
  ...
end
```

And that is just way too much? What do you think?

So we decided to try to fill as much as possible on a single line - which is what happens with lists. We have added this ability to Elixir master just recently. More info here: https://github.com/elixir-lang/elixir/commit/3b7bf4ed537fa2d9f34da735d7c000d77a36f3a5

**Comment by lpil** [comment]
Once things get large I prefer one item per line as it makes it much clearer where each argument/pattern begins.

As a minor addition it's also a bit easier to edit if you use a linewise editor such as vim or emacs :)

**Comment by josevalim** [comment]
@lpil yes, I can also see that. I guess we will only know for sure after we try it. Here is another example:

```elixir
case some_function(
       foo,
       bar,
       baz
     ) do
  ...
```

or:

```elixir
case some_function(foo, bar,
                   baz) do
  ...
```

**Comment by josevalim** [comment]
I guess the above also has something like:

```elixir
case some_function(
  foo,
  bar,
  baz
) do
  ...
```

**Comment by lexmag** [comment]
I think I always use the following in function definitions and function calls (**1.**):
```elixir
case some_function(foo, bar,
                   baz) do

def some_function(foo, bar,
                  baz) do
```
It looks like a different thing than `map = %{` (**2.**) to me. **2.** is about data structures, while the **1.** is not.
Also I think **1.** indentation works better if you have multiline pattern matching in arguments, and `when` conditions in definition.

**Comment by whatyouhide** [comment]
This issue also applies to structs so I will reopen until solved for structs as well.

**Comment by uohzxela** [comment]
@whatyouhide, fix for structs: https://github.com/uohzxela/ex_format/commit/1c863c796f683b0d0a534e1f29eca02a7236bec1

Let me know if there's anything I've missed.

**Comment by whatyouhide** [comment]
Looks good.
