### ISSUE TITLE
test/2,3 in ExUnit should not have parens

### ISSUE THREAD

**Issue by whatyouhide** [uohzxela/ex_format#30]
It's formatted as

```elixir
test("some test") do
  ...
end
```

I think we should not hardcode these, probably all things that take `do...end` should not have parens in their args before the block.

**Comment by uohzxela** [comment]
Thanks for the tip! I have pushed a fix (l[ink](https://github.com/uohzxela/ex_format/commit/4065a3c517d85d9dd237dd7d9db5a9eeadc953a4)) to master, this should be fixed.
