### ISSUE TITLE
Layout-related rules

### ISSUE THREAD

**Issue by uohzxela** [uohzxela/ex_format#4]
- [x] [spaces-indentation](https://github.com/lexmag/elixir-style-guide#spaces-indentation)
- [x] [no-semicolon](https://github.com/lexmag/elixir-style-guide#no-semicolon)
- [x] [spaces-in-code](https://github.com/lexmag/elixir-style-guide#spaces-in-code)
- [x] [no-spaces-in-code](https://github.com/lexmag/elixir-style-guide#no-spaces-in-code)
- [x] [default-arguments](https://github.com/lexmag/elixir-style-guide#default-arguments)
- [x] [no-trailing-whitespaces](https://github.com/lexmag/elixir-style-guide#no-trailing-whitespaces)
- [x] [newline-eof](https://github.com/lexmag/elixir-style-guide#newline-eof)
- [x] [bitstring-segment-options](https://github.com/lexmag/elixir-style-guide#bitstring-segment-options)
- [x] [guard-clauses](https://github.com/lexmag/elixir-style-guide#guard-clauses)
- [x] [multi-line-expr-assignment](https://github.com/lexmag/elixir-style-guide#multi-line-expr-assignment)
- [x] [underscores-in-numerics](https://github.com/lexmag/elixir-style-guide#underscores-in-numerics)
- [x] [quotes-around-atoms](https://github.com/lexmag/elixir-style-guide#quotes-around-atoms)
- [x] [trailing-comma](https://github.com/lexmag/elixir-style-guide#trailing-comma)
- [x] [expression-group-alignment](https://github.com/lexmag/elixir-style-guide#expression-group-alignment)

**Comment by binaryseed** [comment]
In the case of [multi-line-expr-assignment](https://github.com/lexmag/elixir-style-guide#multi-line-expr-assignment), it seems there are two allowed styles. I'd vote for always placing the expression on a new line, since it creates proper indentation alignment with `case` & `end` type expressions, as well as proper indentation of the clauses with the `case`:

```elixir
prefix =
  case base do
    :binary -> "0b"
    :octal -> "0o"
    :hex -> "0x"
  end
```
 
over

```elixir
prefix = case base do
  :binary -> "0b"
  :octal -> "0o"
  :hex -> "0x"
end
```

Also, without the newline, it has inconsistent indentation compared to a pipeline style expression (the `end` has 0 indentation instead of 2):

```elixir
{found, not_found} =
  Enum.map(files, &Path.expand(&1, path))
  |> Enum.partition(&File.exists?/1)
```

**Comment by uohzxela** [comment]
@binaryseed good catch! According to the powers that be, the first style is preferred as well. I have already enforced it in my latest PR which has yet to merge with master.

**Comment by uohzxela** [comment]
Personally, I'm in favour of the first style. I have already enforced it in the latest PR which has yet to merge with master. There may be some special cases that need to be handled though. So that's still up for discussion.

**Comment by whatyouhide** [comment]
@uohzxela informally the team agrees on 

```elixir
prefix =
  case base do
    :binary -> "0b"
    :octal -> "0o"
    :hex -> "0x"
  end
```

being the proper style. We'll try to add it to the style guide as well.
