### ISSUE TITLE
Not all integers should be underscored

### ISSUE THREAD

**Issue by whatyouhide** [uohzxela/ex_format#45]
```elixir
port = 6379
```

should be kept as is but is formatted as

```elixir
port = 6_379
```

Not sure how to tackle this. \cc @josevalim

**Comment by josevalim** [comment]
We had this discussion for Elixir. I think the agreement was after 6 chars?

**Comment by whatyouhide** [comment]
Right, I forgot sorry. Great then :)

**Comment by uohzxela** [comment]
Fix: https://github.com/uohzxela/ex_format/commit/82076a4faf2c1c0d2de5fa0f5a79103a163a3e3d
