### ISSUE TITLE
Format integers as they are written

### ISSUE THREAD

**Issue by whatyouhide** [uohzxela/ex_format#47]
This is kind of a tough one I think. In [Xandra](https://hex.pm/packages/xandra), we use integers with hex notation to represent bytes that have meaning in Cassandra's protocol. We write these as `0x01`, `0x0A`, `0xFF` and so on. The ones with the trailing `0` get rewritten to `0x1`, `0xA` and so on. How should we keep this formatted correctly? It must require changes to Elixir I guess because we need to keep the literal somehow.

\cc @josevalim

**Comment by josevalim** [comment]
Maybe we can store the number of places in the AST?

**Comment by whatyouhide** [comment]
@josevalim yes that sounds like a good approach to me.

**Comment by josevalim** [comment]
I think in order to keep proper error reporting, we may need to send the whole token to the parser and let the parser do the conversion to integer. This means we can also store the whole token in the AST if we want to.

**Comment by uohzxela** [comment]
@josevalim @whatyouhide do we need to store tokens for `?è` and friends as well?

**Comment by josevalim** [comment]
@uohzxela I think so. The token will always be a list with a single element on this case. For hex, it should be a list with everything after `0x`.

@whatyouhide do we want to keep the whole integer and floats for regular integers and floats? The benefit is that then we don't need to format the `_`, we will keep whatever the user uses. Reasonable?
