### ISSUE TITLE
Tuple calls

### ISSUE THREAD

**Issue by whatyouhide** [uohzxela/ex_format#48]
ex_format suffers from the same thing that `Macro.to_string/2` suffered from before https://github.com/elixir-lang/elixir/pull/6418.

```elixir
# This
alias Foo.{Bar, Baz}

# is formatted as
alias Foo.{}(Bar, Baz)

# but should be formatted by ex_format as
alias Foo.{
  Bar,
  Baz,
}
```

**Comment by uohzxela** [comment]
https://github.com/uohzxela/ex_format/commit/424bb98a8f1db50d531f7732ae91288e1d790be9

I wrapped the args inside a tuple syntax so it can handle multiline args as well.
