### ISSUE TITLE
Don't parenthesize key: value syntactic sugar

### ISSUE THREAD

**Issue by whatyouhide** [uohzxela/ex_format#49]
```elixir
{foo, bar, baz: :bong}
```

should be kept as is instead of formatting it as 

```elixir
{foo, bar, [baz: :bong]}
```

**Comment by uohzxela** [comment]
@whatyouhide so the gist is: don't parenthesize keyword list in tuples? Also, is it sufficient to do so only for tuples?

**Comment by whatyouhide** [comment]
Lists also have the same problem, which is part of https://github.com/uohzxela/ex_format/issues/44 as well. Can't think of anything else off the top of my head.

**Comment by uohzxela** [comment]
Reopened issue because stripping parens for keyword list in tuples results in syntax error in some cases:

`{[line: 1], state}` works fine

but `{line: 1, state}` is syntactically incorrect.

Maybe a rule of thumb is to only strip parens if the keyword list is the last element in the tuple.

**Comment by whatyouhide** [comment]
That's not a rule of thumb, it's how Elixir actually works: you can only use keywords as the last element of lists/tuples:

```elixir
iex> [1, 2, c: :d]
[1, 2, {:c, :d}]
```

So yep, we should remove parens only if it's the last element.

**Comment by uohzxela** [comment]
@whatyouhide thanks for clarifying this further :)

**Comment by uohzxela** [comment]
Fixed per this commit: https://github.com/uohzxela/ex_format/commit/4e1e2fd2c1c3927fc2a84fc25b4c5e6533d7b1cc
