### ISSUE TITLE
Syntax-related rules

### ISSUE THREAD

**Issue by uohzxela** [uohzxela/ex_format#5]
- [x] [fun-parens](https://github.com/lexmag/elixir-style-guide#fun-parens)
- [x] [zero-arity-parens](https://github.com/lexmag/elixir-style-guide#zero-arity-parens)
- [x] [anonymous-fun-parens](https://github.com/lexmag/elixir-style-guide#anonymous-fun-parens)
- [x] [binary-operators-eols](https://github.com/lexmag/elixir-style-guide#binary-operators-at-eols) (line splitting)
- [x] [pipeline-indentation](https://github.com/lexmag/elixir-style-guide#pipeline-operator) (line splitting)
- [x] [with-indentation](https://github.com/lexmag/elixir-style-guide#with-indentation)
- [x] [for-indentation](https://github.com/lexmag/elixir-style-guide#for-indentation)
- [x] [hex-literals](https://github.com/lexmag/elixir-style-guide#hex-literals)

**Comment by uohzxela** [comment]
@whatyouhide i'm not a fan of [no-nil-else](https://github.com/lexmag/elixir-style-guide#no-nil-else) rule because it mutates the AST, should we leave it out of the to-do list for now?

**Comment by whatyouhide** [comment]
@uohzxela I am not a fan of that rule either, but it is not something that should concern the formatter, it's something for a linter (like Credo). You can take it out of this list.

**Comment by lpil** [comment]
:+1: Good call

**Comment by uohzxela** [comment]
@whatyouhide, as @lpil suggested in the latest PR, maybe we should leave the [zero-arity-parens](https://github.com/lexmag/elixir-style-guide#zero-arity-parens) rule to be enforced by the programmer so as to avoid changing semantics. What do you think?

However, I think the [fun-parens](https://github.com/lexmag/elixir-style-guide#fun-parens) rule can be implemented without any side effects, will open a different PR for that.

**Comment by whatyouhide** [comment]
@uohzxela we can start by leaving it to the programmer for 0-arity local/imported funs but we can enforce it for remote 0-arity funs (`Mix.env()`) and for functions in pipes (`x |> foo() |> Bar.baz()`). `fun-parens` can be implemented now for sure, please do so in a separate PR.

**Comment by uohzxela** [comment]
@whatyouhide sounds good!
