### ISSUE TITLE
Comments are lost in `case`

### ISSUE THREAD

**Issue by melpon** [uohzxela/ex_format#59]
```elixir
IO.puts ExFormat.format_string("""
case [] do
  # comment 1
  [] -> :ok
  # comment 2
  [_ | _] -> :ok
  # comment 3
end
""")
```

is formatted as

```elixir
case [] do
  [] ->
    :ok
  [_ | _] ->
    :ok
    # comment 3
end
```

**Comment by uohzxela** [comment]
Hey @melpon! Thanks a lot for the bug report. This is an interesting case - the comments are actually preserved in the AST but somehow the formatter didn't manage to display them. Will work on it.

**Comment by uohzxela** [comment]
Just pushed a fix to master: https://github.com/uohzxela/ex_format/commit/d2108116c5f6f1a55fe9c92cbf03da5e1433cedd

Please feel free to verify if it's working on your end, and let me know if there's any problem!

**Comment by melpon** [comment]
It is work perfectly. Thank you for quick fix!
