### ISSUE TITLE
Miscellaneous rules

### ISSUE THREAD

**Issue by uohzxela** [uohzxela/ex_format#6]
- [ ] [module-layout](https://github.com/lexmag/elixir-style-guide#module-layout)
- [ ] [current-module-reference](https://github.com/lexmag/elixir-style-guide#current-module-reference)
- [ ] [defstruct-fields-default](https://github.com/lexmag/elixir-style-guide#defstruct-fields-default)
- [ ] [exception-message](https://github.com/lexmag/elixir-style-guide#exception-message)
- [ ] [exunit-assertion-side](https://github.com/lexmag/elixir-style-guide#exunit-assertion-side)

**Comment by whatyouhide** [comment]
You can take out most of these, that is:

- module-layout: the order is a linting rule not a formatting rule. You can only group together `import`s, `require`s and so on
- current-module-reference: it's a linting rule not a formatting rule
- defstruct-fields-default: it's a linting rule not a formatting rule
- exception-message: it's a linting rule not a formatting rule (and we can't go on changing exception messages for users)
- exunit-assertion-side: we can't change the order of operations and keep semantic equivalence. This is a linting rule anyways.

I would close this issue and maybe open one for the grouping of `import`s and friends.

**Comment by uohzxela** [comment]
Thank you! @whatyouhide
