### ISSUE TITLE
Keyword syntax is formatted incorrectly

### ISSUE THREAD

**Issue by whatyouhide** [uohzxela/ex_format#64]
I first found out that

```elixir
@spec foo([{a, b}]) :: :ok
```

is formatted as

```elixir
@spec foo([a: b]) :: :ok
```

which is incorrect as it changes the semantics. It should not be changed in any way when formatting. Going a bit further, I found out that every two-element tuple is converted to keyword syntax which is incorrect because a "keyword" is a two-element tuple *where the first element is an atom*, not any two-element tuple. For example:

```elixir
[{1, 2}]

# becomes

[1: 2]
```

**Comment by whatyouhide** [comment]
My bad, I was on the wrong branch. This is fixed in master. 👍

**Comment by uohzxela** [comment]
Magic fix 😄
