### ISSUE TITLE
Project documentation & deliverables

### ISSUE THREAD

**Issue by uohzxela** [uohzxela/ex_format#65]
Deliverables:

- [x] ExDoc 
- [x] README
- [x] Mix task
- [x] Escript

Documentation:

- [x] `format/1`
- [x] `mix format`

**Comment by whatyouhide** [comment]
I would:

1. Make `format_string/1` be the *only* function exposed (`fits?` is exposed rn as well)
1. Document it and the `ExFormat` module via `@doc` and `@moduledoc` directly
1. Rename `format_string/1` to `format/1`
1. Finally create the crowd favorite `mix format` task, which takes a list of wildcards and formats all the files that match each wildcard (`mix format lib/**/*.ex config/**/*.exs`). This should only use `format/1` and do the file reading/writing "in private" without exposing anything
1. Write docs for `mix format`
1. Write a nice concise readme that shows what this project is, what it does, how to use it, and points to the exdoc documentation

**Comment by uohzxela** [comment]
@whatyouhide thanks for your suggestions. Would it be a good idea to create an escript like `./ex_format`? I read from the [docs](https://hexdocs.pm/mix/master/Mix.Tasks.Escript.Build.html) that it embeds Elixir so the end-user doesn't need to build Elixir v1.6 from source to use the formatter. Thoughts?

**Comment by whatyouhide** [comment]
An escript is fine too as long as we make the project usable, yep.

**Comment by uohzxela** [comment]
@whatyouhide great, I've updated the checklist as above.
