### ISSUE TITLE
Strings that use <> for continuation should align to the string, not the line

### ISSUE THREAD

**Issue by KronicDeth** [uohzxela/ex_format#89]
# Current behaviors

![screen shot 2017-09-01 at 8 45 34 am](https://user-images.githubusercontent.com/298259/29972920-7421d43e-8ef3-11e7-80ea-1492823c01ee.png)

## Formatted with IntelliJ Elixir

The string that is too long for the column limit was split by the user using `<>`.  The formatter aligns the continued string with the first string (**NOTE: the Elixir style guide says to indent the continuation, so this differs in that the continuation indent is turned off for strings**)

```elixir
   %Ecto.Association.NotLoaded{} ->
        raise ArgumentError,
              "`%Schedule{}` `job_series` must be loaded " <>
              "before checking if `#{aliased(InterpreterProfile)}` can show a `%Schedule{}`"
````

## Formatted with `ex_format`

The string argument is brought up to the first line and the continued string is continuation indented relative to the call/line (start of `raise`) instead of the left operand (the first string), so it's less obvious the Strings are united.

```elixir
      %Ecto.Association.NotLoaded{} ->
        raise ArgumentError, "`%Schedule{}` `job_series` must be loaded " <>
          "before checking if `#{aliased(InterpreterProfile)}` can show a `%Schedule{}`"
```

# Potential changes

## When `<>` continued strings are detected, leave as multiple line call, but indent using Elixir Style guide

```elixir
   %Ecto.Association.NotLoaded{} ->
        raise ArgumentError,
              "`%Schedule{}` `job_series` must be loaded " <>
                "before checking if `#{aliased(InterpreterProfile)}` can show a `%Schedule{}`"
```

## Ident continued String relative to start of string

```elixir
      %Ecto.Association.NotLoaded{} ->
        raise ArgumentError, "`%Schedule{}` `job_series` must be loaded " <>
                               "before checking if `#{aliased(InterpreterProfile)}` can show a `%Schedule{}`"
```

**Comment by lpil** [comment]
Does this conform to the style guide? I can't find this anywhere in it. If it is not I believe we should treat `<>` the same as any other operator.

**Comment by KronicDeth** [comment]
@lpil As far as I could find, there's no special call-out in the style guide for `<>` for Strings, but as a human, trying to read a String that had to split across lines, it's easier if I can read it as an aligned wall of text, it's one of the reason Elixir has heredocs, but heredocs have the problem that the newlines are really in the string, so `<>` a bunch of Strings is a work-around for needing a String that doesn't have newlines where the code has newlines.

So, should I open an issue with the the style-guide first?

**Comment by lpil** [comment]
> but as a human, trying to read a String that had to split across lines, it's easier if I can read it as an aligned wall of text

This is a matter of personal taste :)

> So, should I open an issue with the the style-guide first?

I think so!

**Comment by uohzxela** [comment]
As mentioned in the previous issue https://github.com/uohzxela/ex_format/issues/90#issuecomment-326715312, we have a new formatter. 

Its current behavior for your reference:

```
  %Ecto.Association.NotLoaded{} ->
    raise ArgumentError,
          "`%Schedule{}` `job_series` must be loaded " <>
            "before checking if `#{aliased(InterpreterProfile)}` can show a `%Schedule{}`"
```
