### ISSUE TITLE
Getting "(SyntaxError) syntax error before: '&&'" even though '&&' is not present in file

### ISSUE THREAD

**Issue by kimsaehun** [uohzxela/ex_format#91]
Hello, I am getting a syntax error when running ExFormat and I am unsure of why it is happening. I have posted some details of my problem.

Here is the error I get when running ExFormat:
> Formatting apps/bors_worker/lib/batcher.ex ... ** (SyntaxError) nofile:293: syntax error before: '&&' 
(ex_format) lib/ex_format.ex:26: ExFormat.format/1 
(ex_format) lib/mix/tasks/format.ex:23: Mix.Tasks.Format.format_file/1
(ex_format) lib/cli.ex:36: anonymous fn/1 in ExFormat.CLI.run/1
(elixir) lib/enum.ex:675: Enum."-each/2-lists^foreach/1-0-"/2
(elixir) lib/enum.ex:675: Enum.each/2
(elixir) lib/kernel/cli.ex:90: anonymous fn/3 in Kernel.CLI.exec_fun/2

The command I use to run ExFormat is:
> ~/.mix/escripts/ex_format apps/bors_worker/lib/batcher.ex

In case it is useful, here is my output of `elixirc --version`
>Erlang/OTP 20 [erts-9.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]
Elixir 1.5.2

In addition, the file I am formatting can be found [here](https://github.com/kimsaehun/bors-ng/blob/master/apps/bors_worker/lib/batcher.ex).

**Comment by uohzxela** [comment]
Hi @kimsaehun! Thanks for using my formatter :) It is meant as a prototype and is not production-ready. Please have a look at the [latest code formatter](https://github.com/whatyouhide/code_formatter) that's under development by the Elixir core team. They also added a [mix task](https://github.com/elixir-lang/elixir/pull/6642/files) for it recently. Happy formatting!

**Comment by whatyouhide** [comment]
@uohzxela might be a good idea to say that in the README so folks are redirected towards the Elixir formatter :).

**Comment by kimsaehun** [comment]
Thanks for letting me know!
